In [1]:
import math
import os
import pandas as pd
import numpy as np
from sklearn.ensemble import ExtraTreesRegressor, RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn import metrics
from sklearn.metrics import make_scorer
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split, KFold, GridSearchCV, RandomizedSearchCV
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
from mlxtend.regressor import StackingRegressor
from xgboost import XGBRegressor, XGBRFRegressor

In [2]:
def read_data(filename):

    data=pd.read_csv('withindata/'+filename)
    data=data.drop(['name', 'version', 'name.1'], axis='columns')

    features=data.drop(['bug'], axis='columns')
    label=data['bug']

    test_features=features.values.reshape(-1,20)
    test_label=label.values.reshape(-1,1)

    return test_features, test_label

In [3]:
def mean_relative_error(actual, predicted):
    rel_err=[]
    actual,predicted=np.array(actual), np.array(predicted)
    for i in range(0,len(actual)):
        err=abs(actual[i]-predicted[i])/(actual[i]+1)
        rel_err.append(err)
    return np.mean(rel_err)

In [32]:
def run_techniques(filename): 
    
    features, label = read_data(filename)
    train_features, test_features, train_label, test_label = train_test_split(features, label, test_size=0.2)

    stravgmre,stravgmretest=[],[]
    stravgmae,stravgmaetest=[],[]
    stravgrmse,stravgrmsetest=[],[]
    
    stravgmre2,stravgmretest2=[],[]
    stravgmae2,stravgmaetest2=[],[]
    stravgrmse2,stravgrmsetest2=[],[]

    dtravgmre,dtravgmretest=[],[]
    dtravgmae,dtravgmaetest=[],[]
    dtravgrmse,dtravgrmsetest=[],[]

    rfravgmre,rfravgmretest=[],[]
    rfravgmae,rfravgmaetest=[],[]
    rfravgrmse,rfravgrmsetest=[],[]

    etravgmre,etravgmretest=[],[]
    etravgmae,etravgmaetest=[],[]
    etravgrmse,etravgrmsetest=[],[]

    knnavgmre,knnavgmretest=[],[]
    knnavgmae,knnavgmaetest=[],[]
    knnavgrmse,knnavgrmsetest=[],[]

    svravgmre,svravgmretest=[],[]
    svravgmae,svravgmaetest=[],[]
    svravgrmse,svravgrmsetest=[],[]

    bavgmre,bavgmretest=[],[]
    bavgmae,bavgmaetest=[],[]
    bavgrmse,bavgrmsetest=[],[]

    import warnings
    warnings.filterwarnings("ignore")

    for run in range(0,30):
        print('run: ', run+1)

        kf=KFold(n_splits=10,shuffle=True)
        i=1

        strmre,strmretest=[],[]
        strmae,strmaetest=[],[]
        strrmse,strrmsetest=[],[]
        
        strmre2,strmretest2=[],[]
        strmae2,strmaetest2=[],[]
        strrmse2,strrmsetest2=[],[]

        dtrmre,dtrmretest=[],[]
        dtrmae,dtrmaetest=[],[]
        dtrrmse,dtrrmsetest=[],[]

        rfrmre,rfrmretest=[],[]
        rfrmae,rfrmaetest=[],[]
        rfrrmse,rfrrmsetest=[],[]

        etrmre,etrmretest=[],[]
        etrmae,etrmaetest=[],[]
        etrrmse,etrrmsetest=[],[]

        knnmre,knnmretest=[],[]
        knnmae,knnmaetest=[],[]
        knnrmse,knnrmsetest=[],[]

        svrmre,svrmretest=[],[]
        svrmae,svrmaetest=[],[]
        svrrmse,svrrmsetest=[],[]

        bmre,bmretest=[],[]
        bmae,bmaetest=[],[]
        brmse,brmsetest=[],[]

        for train_index,test_index in kf.split(train_features):
            print('fold number: ', i)

            x_train,x_test=train_features[train_index],train_features[test_index]
            y_train,y_test=train_label[train_index],train_label[test_index]
            
            params_tree = {
                'n_estimators':[50,126],
                'min_samples_leaf':[30,50],
                'max_depth':[20,50]
                }
            
            params_d_tree = {
                'max_depth':[20,50]
                }
            
            params_knn = {
                'n_neighbors':[5,10]
                }
            
            params_svr ={
                'C':[5,10],
                'gamma':[0.001,0.1,1]
                }
            
            params_xgb = {
                'max_depth':[10,50],
                'min_child_weight':[1,6]
                }
            
            params_1 = {
                'svr__C':[0.001,0.1,1,5,10],
                'svr__gamma':[0.001, 0.1, 0.5,1],
                'extratreesregressor__n_estimators':[50,100,126,200],
                'extratreesregressor__min_samples_leaf':[20,30,50,10],
                'kneighborsregressor__n_neighbors':[5,7,10,15],
                'randomforestregressor__max_depth':[10,20,30,50],
                'randomforestregressor__n_estimators':[50,100,126,300],
                'meta_regressor__C':[0.001,0.1,1,5,10],
                'meta_regressor__gamma':[0.001,0.1,0.5,1],
                'meta_regressor__kernel':['rbf','linear']
                }
            
            params_2 = {
                'svr__C':[0.001,0.1,1,5,10],
                'svr__gamma':[0.001, 0.1, 0.5,1],
                'extratreesregressor__n_estimators':[50,100,126,200],
                'extratreesregressor__min_samples_leaf':[20,30,50,10],
                'kneighborsregressor__n_neighbors':[5,7,10,15],
                'randomforestregressor__max_depth':[10,20,30,50],
                'randomforestregressor__n_estimators':[50,100,126,300],
                'meta_regressor__max_depth':[10,20,30,50],
                'meta_regressor__n_estimators':[20,50,100,150,500]
                }
            
            print('DTR')
            rand_search_dtr = RandomizedSearchCV(DecisionTreeRegressor(), params_d_tree, cv=5)
            rand_search_dtr.fit(x_train, y_train)
            best_tuned_dtr = rand_search_dtr.best_estimator_
            y_pred = best_tuned_dtr.predict(test_features)
            test_pred = best_tuned_dtr.predict(x_test)
            #testing errors
            dtrmretest.append(mean_relative_error(y_test,test_pred))
            dtrmaetest.append(metrics.mean_absolute_error(y_test,test_pred))
            dtrrmsetest.append(math.sqrt(metrics.mean_squared_error(y_test,test_pred)))
            #validation errors
            dtrmre.append(mean_relative_error(test_label,y_pred))
            dtrmae.append(metrics.mean_absolute_error(test_label,y_pred))
            dtrrmse.append(math.sqrt(metrics.mean_squared_error(test_label,y_pred)))
            
            print('RFR')
            rand_search_rfr = RandomizedSearchCV(RandomForestRegressor(), params_tree, cv=5)
            rand_search_rfr.fit(x_train, y_train)
            best_tuned_rfr = rand_search_rfr.best_estimator_
            y_pred = best_tuned_rfr.predict(test_features)
            test_pred = best_tuned_rfr.predict(x_test)
            #testing errors
            rfrmretest.append(mean_relative_error(y_test,test_pred))
            rfrmaetest.append(metrics.mean_absolute_error(y_test,test_pred))
            rfrrmsetest.append(math.sqrt(metrics.mean_squared_error(y_test,test_pred)))
            #validation errors
            rfrmre.append(mean_relative_error(test_label,y_pred))
            rfrmae.append(metrics.mean_absolute_error(test_label,y_pred))
            rfrrmse.append(math.sqrt(metrics.mean_squared_error(test_label,y_pred)))
            
            print('ETR')
            rand_search_etr = RandomizedSearchCV(ExtraTreesRegressor(), params_tree, cv=5)
            rand_search_etr.fit(x_train, y_train)
            best_tuned_etr = rand_search_etr.best_estimator_
            y_pred = best_tuned_etr.predict(test_features)
            test_pred = best_tuned_etr.predict(x_test)
            #testing errors
            etrmretest.append(mean_relative_error(y_test,test_pred))
            etrmaetest.append(metrics.mean_absolute_error(y_test,test_pred))
            etrrmsetest.append(math.sqrt(metrics.mean_squared_error(y_test,test_pred)))
            #validation errors
            etrmre.append(mean_relative_error(test_label,y_pred))
            etrmae.append(metrics.mean_absolute_error(test_label,y_pred))
            etrrmse.append(math.sqrt(metrics.mean_squared_error(test_label,y_pred)))
            
            print('KNN')
            rand_search_knn = RandomizedSearchCV(KNeighborsRegressor(), params_knn, cv=5)
            rand_search_knn.fit(x_train, y_train)
            best_tuned_knn = rand_search_knn.best_estimator_
            y_pred = best_tuned_knn.predict(test_features)
            test_pred = best_tuned_knn.predict(x_test)
            #testing errors
            knnmretest.append(mean_relative_error(y_test,test_pred))
            knnmaetest.append(metrics.mean_absolute_error(y_test,test_pred))
            knnrmsetest.append(math.sqrt(metrics.mean_squared_error(y_test,test_pred)))
            #validation errors
            knnmre.append(mean_relative_error(test_label,y_pred))
            knnmae.append(metrics.mean_absolute_error(test_label,y_pred))
            knnrmse.append(math.sqrt(metrics.mean_squared_error(test_label,y_pred)))
            
            print('SVR')
            rand_search_svr = RandomizedSearchCV(SVR(), params_svr, cv=5)
            rand_search_svr.fit(x_train, y_train)
            best_tuned_svr = rand_search_svr.best_estimator_
            y_pred = best_tuned_svr.predict(test_features)
            test_pred = best_tuned_svr.predict(x_test)
            #testing errors
            svrmretest.append(mean_relative_error(y_test,test_pred))
            svrmaetest.append(metrics.mean_absolute_error(y_test,test_pred))
            svrrmsetest.append(math.sqrt(metrics.mean_squared_error(y_test,test_pred)))
            #validation errors
            svrmre.append(mean_relative_error(test_label,y_pred))
            svrmae.append(metrics.mean_absolute_error(test_label,y_pred))
            svrrmse.append(math.sqrt(metrics.mean_squared_error(test_label,y_pred)))
            
#             print('XGB')
#             rand_search_xgb = RandomizedSearchCV(XGBRegressor(silent=True), params_xgb, cv=5, n_jobs = 4)
#             print('fittinh')
#             rand_search_xgb.fit(x_train, y_train)
#             print('predicting')
#             best_tuned_xgb = rand_search_xgb.best_estimator_
#             y_pred = best_tuned_xgb.predict(test_features)
#             test_pred = best_tuned_xgb.predict(x_test)
#             #testing errors
#             bmretest.append(mean_relative_error(y_test,test_pred))
#             bmaetest.append(metrics.mean_absolute_error(y_test,test_pred))
#             brmsetest.append(math.sqrt(metrics.mean_squared_error(y_test,test_pred)))
#             #validation errors
#             bmre.append(mean_relative_error(test_label,y_pred))
#             bmae.append(metrics.mean_absolute_error(test_label,y_pred))
#             brmse.append(math.sqrt(metrics.mean_squared_error(test_label,y_pred)))
            
            print('SR')
            reg1=SVR()
            reg2=ExtraTreesRegressor()
            reg3=KNeighborsRegressor()
            reg4=RandomForestRegressor()
            rand_search_sr = RandomizedSearchCV(StackingRegressor(store_train_meta_features=True,regressors=[reg1,reg2,reg3,reg4], meta_regressor=SVR()), params, cv =5)
            print('fitting')
            rand_search_sr.fit(x_train, y_train)
            print('predicting')
            best_tuned_sr = rand_search_sr.best_estimator_
            print(best_tuned_sr.train_meta_features_[0])
            y_pred = best_tuned_sr.predict(test_features)
            test_pred = best_tuned_sr.predict(x_test)
            #testing errors
            strmretest.append(mean_relative_error(y_test,test_pred))
            strmaetest.append(metrics.mean_absolute_error(y_test,test_pred))
            strrmsetest.append(math.sqrt(metrics.mean_squared_error(y_test,test_pred)))
            #validation errors
            strmre.append(mean_relative_error(test_label,y_pred))
            strmae.append(metrics.mean_absolute_error(test_label,y_pred))
            strrmse.append(math.sqrt(metrics.mean_squared_error(test_label,y_pred)))

            i=i+1

        dtravgmre.append(np.mean(dtrmre))
        dtravgmae.append(np.mean(dtrmae))
        dtravgrmse.append(np.mean(dtrrmse))
        dtravgmretest.append(np.mean(dtrmretest))
        dtravgmaetest.append(np.mean(dtrmaetest))
        dtravgrmsetest.append(np.mean(dtrrmsetest))

        rfravgmre.append(np.mean(rfrmre))
        rfravgmae.append(np.mean(rfrmae))
        rfravgrmse.append(np.mean(rfrrmse))
        rfravgmretest.append(np.mean(rfrmretest))
        rfravgmaetest.append(np.mean(rfrmaetest))
        rfravgrmsetest.append(np.mean(rfrrmsetest))

        etravgmre.append(np.mean(etrmre))
        etravgmae.append(np.mean(etrmae))
        etravgrmse.append(np.mean(etrrmse))
        etravgmretest.append(np.mean(etrmretest))
        etravgmaetest.append(np.mean(etrmaetest))
        etravgrmsetest.append(np.mean(etrrmsetest))

        knnavgmre.append(np.mean(knnmre))
        knnavgmae.append(np.mean(knnmae))
        knnavgrmse.append(np.mean(knnrmse))
        knnavgmretest.append(np.mean(knnmretest))
        knnavgmaetest.append(np.mean(knnmaetest))
        knnavgrmsetest.append(np.mean(knnrmsetest))

        svravgmre.append(np.mean(svrmre))
        svravgmae.append(np.mean(svrmae))
        svravgrmse.append(np.mean(svrrmse))
        svravgmretest.append(np.mean(svrmretest))
        svravgmaetest.append(np.mean(svrmaetest))
        svravgrmsetest.append(np.mean(svrrmsetest))

#         bavgmre.append(np.mean(bmre))
#         bavgmae.append(np.mean(bmae))
#         bavgrmse.append(np.mean(brmse))
#         bavgmretest.append(np.mean(bmretest))
#         bavgmaetest.append(np.mean(bmaetest))
#         bavgrmsetest.append(np.mean(brmsetest))

        stravgmre.append(np.mean(strmre))
        stravgmae.append(np.mean(strmae))
        stravgrmse.append(np.mean(strrmse))
        stravgmretest.append(np.mean(strmretest))
        stravgmaetest.append(np.mean(strmaetest))
        stravgrmsetest.append(np.mean(strrmsetest))

        print('dtr: mre: ', np.mean(dtrmre), ' mae: ', np.mean(dtrmae), ' rmse: ', np.mean(dtrrmse))
        print('test dtr: mre: ', np.mean(dtrmretest), ' mae: ', np.mean(dtrmaetest), ' rmse: ', np.mean(dtrrmsetest))        
        print('rfr: mre: ', np.mean(rfrmre), ' mae: ', np.mean(rfrmae), ' rmse: ', np.mean(rfrrmse))
        print('test rfr: mre: ', np.mean(rfrmretest), ' mae: ', np.mean(rfrmaetest), ' rmse: ', np.mean(rfrrmsetest))
        print('etr: mre: ', np.mean(etrmre), ' mae: ', np.mean(etrmae), ' rmse: ', np.mean(etrrmse))
        print('test etr: mre: ', np.mean(etrmretest), ' mae: ', np.mean(etrmaetest), ' rmse: ', np.mean(etrrmsetest))
        print('knn: mre: ', np.mean(knnmre), ' mae: ', np.mean(knnmae), ' rmse: ', np.mean(knnrmse))
        print('test knn: mre: ', np.mean(knnmretest), ' mae: ', np.mean(knnmaetest), ' rmse: ', np.mean(knnrmsetest))
        print('svr: mre: ', np.mean(svrmre), ' mae: ', np.mean(svrmae), ' rmse: ', np.mean(svrrmse))
        print('test svr: mre: ', np.mean(svrmretest), ' mae: ', np.mean(svrmaetest), ' rmse: ', np.mean(svrrmsetest))
#         print('xgb: mre: ', np.mean(bmre), ' mae: ', np.mean(bmae), ' rmse: ', np.mean(brmse))
#         print('test xgb: mre: ', np.mean(bmretest), ' mae: ', np.mean(bmaetest), ' rmse: ', np.mean(brmsetest))
        print('str: mre: ', np.mean(strmre), ' mae: ', np.mean(strmae), ' rmse: ', np.mean(strrmse))
        print('test str: mre: ', np.mean(strmretest), ' mae: ', np.mean(strmaetest), ' rmse: ', np.mean(strrmsetest))

    print('-------------------------------------------------------------------------------------------')
    print('avg dtr: mre: ', np.mean(dtravgmre), ' mae: ', np.mean(dtravgmae), ' rmse: ', np.mean(dtravgrmse))
    print('test avg dtr: mre: ', np.mean(dtravgmretest), ' mae: ', np.mean(dtravgmaetest), ' rmse: ', np.mean(dtravgrmsetest))
    print('avg rfr: mre: ', np.mean(rfravgmre), ' mae: ', np.mean(rfravgmae), ' rmse: ', np.mean(rfravgrmse))
    print('test avg rfr: mre: ', np.mean(rfravgmretest), ' mae: ', np.mean(rfravgmaetest), ' rmse: ', np.mean(rfravgrmsetest))
    print('avg etr: mre: ', np.mean(etravgmre), ' mae: ', np.mean(etravgmae), ' rmse: ', np.mean(etravgrmse))
    print('test avg etr: mre: ', np.mean(etravgmretest), ' mae: ', np.mean(etravgmaetest), ' rmse: ', np.mean(etravgrmsetest))
    print('avg knn: mre: ', np.mean(knnavgmre), ' mae: ', np.mean(knnavgmae), ' rmse: ', np.mean(knnavgrmse))
    print('test avg knn: mre: ', np.mean(knnavgmretest), ' mae: ', np.mean(knnavgmaetest), ' rmse: ', np.mean(knnavgrmsetest))
    print('avg svr: mre: ', np.mean(svravgmre), ' mae: ', np.mean(svravgmae), ' rmse: ', np.mean(svravgrmse))
    print('test avg svr: mre: ', np.mean(svravgmretest), ' mae: ', np.mean(svravgmaetest), ' rmse: ', np.mean(svravgrmsetest))
#     print('avg xgb: mre: ', np.mean(bavgmre), ' mae: ', np.mean(bavgmae), ' rmse: ', np.mean(bavgrmse))
#     print('test avg xgb: mre: ', np.mean(bavgmretest), ' mae: ', np.mean(bavgmaetest), ' rmse: ', np.mean(bavgrmsetest))
    print('avg str: mre: ', np.mean(stravgmre), ' mae: ', np.mean(stravgmae), ' rmse: ', np.mean(stravgrmse))
    print('test avg str: mre: ', np.mean(stravgmretest), ' mae: ', np.mean(stravgmaetest), ' rmse: ', np.mean(stravgrmsetest))

    with open('results-'+ os.path.splitext(filename)[0] +'.txt', 'w') as f:
                        f.write("validation results:\n")
                        f.write("mre, mae, rmse\n")
                        f.write("dtr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(dtravgmre),np.std(dtravgmre),
                                                                            np.mean(dtravgmae), np.std(dtravgmae),
                                                                            np.mean(dtravgrmse), np.std(dtravgrmse)))
                        f.write("rfr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(rfravgmre),np.std(rfravgmre),
                                                                            np.mean(rfravgmae), np.std(rfravgmae),
                                                                            np.mean(rfravgrmse), np.std(rfravgrmse)))
                        f.write("etr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(etravgmre),np.std(etravgmre),
                                                                            np.mean(etravgmae), np.std(etravgmae),
                                                                            np.mean(etravgrmse), np.std(etravgrmse)))
                        f.write("knn: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(knnavgmre),np.std(knnavgmre),
                                                                            np.mean(knnavgmae), np.std(knnavgmae),
                                                                            np.mean(knnavgrmse), np.std(knnavgrmse)))
                        f.write("svr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(svravgmre),np.std(svravgmre),
                                                                            np.mean(svravgmae), np.std(svravgmae),
                                                                            np.mean(svravgrmse), np.std(svravgrmse)))
#                         f.write("xgb: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(bavgmre),np.std(bavgmre),
#                                                                             np.mean(bavgmae), np.std(bavgmae),
#                                                                             np.mean(bavgrmse), np.std(bavgrmse)))
                        f.write("str: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(stravgmre),np.std(stravgmre),
                                                                            np.mean(stravgmae), np.std(stravgmae),
                                                                            np.mean(stravgrmse), np.std(stravgrmse)))
                        f.write("testing results:\n")
                        f.write("mre, mae, rmse\n")
                        f.write("dtr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(dtravgmretest),np.std(dtravgmretest),
                                                                            np.mean(dtravgmaetest), np.std(dtravgmaetest),
                                                                            np.mean(dtravgrmsetest), np.std(dtravgrmsetest)))
                        f.write("rfr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(rfravgmretest),np.std(rfravgmretest),
                                                                            np.mean(rfravgmaetest), np.std(rfravgmaetest),
                                                                            np.mean(rfravgrmsetest), np.std(rfravgrmsetest)))
                        f.write("etr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(etravgmretest),np.std(etravgmretest),
                                                                            np.mean(etravgmaetest), np.std(etravgmaetest),
                                                                            np.mean(etravgrmsetest), np.std(etravgrmsetest)))
                        f.write("knn: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(knnavgmretest),np.std(knnavgmretest),
                                                                            np.mean(knnavgmaetest), np.std(knnavgmaetest),
                                                                            np.mean(knnavgrmsetest), np.std(knnavgrmsetest)))
                        f.write("svr: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(svravgmretest),np.std(svravgmretest),
                                                                            np.mean(svravgmaetest), np.std(svravgmaetest),
                                                                            np.mean(svravgrmsetest), np.std(svravgrmsetest)))
#                         f.write("xgb: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(bavgmretest),np.std(bavgmretest),
#                                                                             np.mean(bavgmaetest), np.std(bavgmaetest),
#                                                                             np.mean(bavgrmsetest), np.std(bavgrmsetest)))
                        f.write("str: %s(%s) & %s(%s) & %s(%s)\n"% (np.mean(stravgmretest),np.std(stravgmretest),
                                                                            np.mean(stravgmaetest), np.std(stravgmaetest),
                                                                            np.mean(stravgrmsetest), np.std(stravgrmsetest)))

In [33]:
for filename in os.listdir('withindata'):
    if '.csv' in filename:
        print(filename)
        run_techniques(filename)

ant-1.7.csv
run:  1
fold number:  1
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09989081 0.80649835 0.4        0.22333333]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.8736967  0.57142857 0.14083433]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000082 0.5693508  2.26666667 0.48666667]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10025425 0.65245316 0.46666667 0.26      ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09973785 0.67305466 0.46666667 0.3015873 ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09998899 0.86122718 0.4        0.17460317]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0998531  0.86214672 0.5        0.31340766]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09984443 0.71709082 0.28571429 0.28      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10050033 0.81612524 0.46666667 0.1984127 ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitt

ETR
KNN
SVR
SR
fitting
predicting
[0.09979884 0.64629824 0.2        0.28571429]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09988183 0.56411587 0.6        0.26220037]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10043849 0.7702916  1.57142857 0.66      ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09992676 0.58580693 0.4        0.23809524]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10002246 0.7647071  0.2        0.21      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10033217 0.83915374 0.46666667 0.29566088]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09997674 0.85965692 0.26666667 0.38      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1000906  0.56722286 0.53333333 0.23015873]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10010574 0.83408216 0.46666667 0.30666667]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000067 0.71012196 0.5   

ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.49675508 1.8        0.5679387 ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.83393375 0.71428571 0.32      ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0999225  0.8906476  0.71428571 0.32333333]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10014373 0.87859219 0.5        0.19      ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10029645 0.68846093 0.4        0.25873397]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09956232 0.65910392 0.4        0.36370648]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10001744 0.83735719 0.71428571 0.38      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10050036 0.60649097 0.28571429 0.13274143]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10050031 0.73753332 0.4        0.25396825]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09977122 0.63558591 0.5   

ETR
KNN
SVR
SR
fitting
predicting
[0.09945529 0.93260111 0.5        0.32539683]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09993753 0.59559481 0.5        0.19      ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09988558 0.79830796 0.46666667 0.19047619]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10050016 0.5022824  0.5        0.18      ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10008143 0.70497117 0.2        0.2       ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10032596 0.91411751 0.5        0.39      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10025024 0.70342904 0.57142857 0.18      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.53302332 1.42857143 0.75968443]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10001448 0.69411152 0.5        0.19276819]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09993967 0.77581631 1.    

ETR
KNN
SVR
SR
fitting
predicting
[0.09990462 0.75182258 0.46666667 0.27440762]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09970055 0.8049073  0.4        0.33300236]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1000304  0.82769169 0.71428571 0.36291677]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09990098 0.62953608 0.4        0.31333333]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09933113 0.84157489 0.3        0.25975283]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10050037 0.48855209 0.57142857 0.29223801]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10044001 0.80775517 0.71428571 0.38589234]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09963914 0.46763918 0.46666667 0.32049817]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09970837 0.63222078 0.46666667 0.1       ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000123 0.80703892 2.    

ETR
KNN
SVR
SR
fitting
predicting
[0.09974911 0.73229344 0.71428571 0.24      ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09967947 0.8901376  0.57142857 0.27      ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10014338 0.87966402 0.46666667 0.27143905]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10028496 0.89763131 0.5        0.25665043]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09995607 0.88863637 0.5        0.3063649 ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09931757 0.73687312 0.57142857 0.26993562]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09982744 0.63505025 2.26666667 0.74470899]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09978988 0.7652934  0.4        0.35714286]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09975177 0.64288017 0.71428571 0.22      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09994088 0.76375686 0.4   

ETR
KNN
SVR
SR
fitting
predicting
[0.09961132 0.88464377 0.57142857 0.33121781]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.7758355  0.5        0.19617517]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10032171 0.65915535 0.4        0.26      ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09973108 0.85947638 0.4        0.27734385]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10011315 0.55265284 0.71428571 0.23809524]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09976232 0.89021528 0.46666667 0.38317649]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.4562865  1.57142857 0.91      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09977031 0.66483073 0.53333333 0.3       ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10006943 0.87027456 0.4        0.32      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09994129 0.66375094 0.6   

ETR
KNN
SVR
SR
fitting
predicting
[0.10021813 0.63812771 0.46666667 0.2       ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10028182 0.63269991 0.4        0.12813415]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10027832 0.81471548 0.4        0.23666667]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09996917 0.77938487 0.6        0.27333333]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09957312 0.64596284 0.71428571 0.23809524]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1001891  0.79289341 0.5        0.33333333]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09988008 0.51370783 1.8        0.49      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10050024 0.84192842 0.46666667 0.23270008]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10010832 0.65074419 0.33333333 0.17333333]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09993871 0.5889623  0.7142

ETR
KNN
SVR
SR
fitting
predicting
[0.05799075 0.47825912 0.06666667 0.41501362]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09997476 0.37482999 0.2        0.1       ]
dtr: mre:  0.557349246053016  mae:  1.1187392055267702  rmse:  3.072572759367055
test dtr: mre:  0.4857338776511709  mae:  0.7737595737595738  rmse:  1.7014204849293697
rfr: mre:  0.46691895147811735  mae:  0.9612949028392924  rmse:  2.5146833361677237
test rfr: mre:  0.4081116300949964  mae:  0.6744320665249603  rmse:  1.3455934597010497
etr: mre:  0.47304733945819255  mae:  0.9711148697375247  rmse:  2.5429151989587604
test etr: mre:  0.4188973750620863  mae:  0.6863133115747525  rmse:  1.3460337123303048
knn: mre:  0.4395279684978631  mae:  0.9487564766839378  rmse:  2.578038682199592
test knn: mre:  0.4062080471742126  mae:  0.6796586746586746  rmse:  1.3958488209294502
svr: mre:  0.42888173270043534  mae:  0.9550419138110445  rmse:  2.6224001471934124
test svr: mre:  0.31359787222567453  mae:  0.600

ETR
KNN
SVR
SR
fitting
predicting
[0.10042141 0.41703709 0.         0.18253968]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09987964 0.39469553 0.         0.26991053]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.05296297 0.40722567 0.13333333 0.3182952 ]
dtr: mre:  0.5369881824446769  mae:  1.0909326424870467  rmse:  2.9715460138956393
test dtr: mre:  0.5458427060332391  mae:  0.8582251082251082  rmse:  1.9313711607318957
rfr: mre:  0.46760542188934673  mae:  0.9599874160428643  rmse:  2.506589684252145
test rfr: mre:  0.4224738360684336  mae:  0.688940736940868  rmse:  1.3896006212753007
etr: mre:  0.4736493606002661  mae:  0.9704064778613537  rmse:  2.5371715761992513
test etr: mre:  0.4266180005055006  mae:  0.6951394125560573  rmse:  1.3749274402305225
knn: mre:  0.4396609479000939  mae:  0.9492227979274611  rmse:  2.579918208200799
test knn: mre:  0.4156439636633588  mae:  0.6959307359307358  rmse:  1.4577045276392189
svr: mre:  0.4360264899030452

ETR
KNN
SVR
SR
fitting
predicting
[0.10003071 0.40333052 0.2        0.21540672]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09987188 0.31208938 0.2        0.13492063]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000794 0.42667313 0.1        0.38096303]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0271047  0.35870934 0.13333333 0.23333333]
dtr: mre:  0.5022037174109713  mae:  1.0488773747841105  rmse:  2.940374163780368
test dtr: mre:  0.4493933843301581  mae:  0.724042624042624  rmse:  1.7625654670173276
rfr: mre:  0.46961282027319645  mae:  0.9618525177441682  rmse:  2.50754216402974
test rfr: mre:  0.42189668604045893  mae:  0.6899225559231901  rmse:  1.3833545323208438
etr: mre:  0.4722222463902779  mae:  0.9690630658207496  rmse:  2.535280112375788
test etr: mre:  0.42441592233106923  mae:  0.6938308384689046  rmse:  1.3653480407848528
knn: mre:  0.43845510066333715  mae:  0.9471502590673575  rmse:  2.5779607210061535
test knn: mr

ETR
KNN
SVR
SR
fitting
predicting
[0.10012088 0.41267343 0.1        0.2       ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10009278 0.41798578 0.1        0.18      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10050636 0.40568051 0.2        0.15873016]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10013271 0.40798502 0.13333333 0.07      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09979871 0.4237762  0.         0.17      ]
dtr: mre:  0.5169069597942209  mae:  1.083937823834197  rmse:  2.9972269222293924
test dtr: mre:  0.4201176156063374  mae:  0.7078921078921079  rmse:  1.6329578644853424
rfr: mre:  0.46643828883930805  mae:  0.9598021772095222  rmse:  2.5075955761559605
test rfr: mre:  0.41620018995677566  mae:  0.6864732027328111  rmse:  1.367314880567
etr: mre:  0.4724498483301594  mae:  0.9698783154446842  rmse:  2.539338914962703
test etr: mre:  0.4240191613902756  mae:  0.6966746007144412  rmse:  1.34506385935

ETR
KNN
SVR
SR
fitting
predicting
[0.10024426 0.42618177 0.         0.19409009]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0999771  0.34734002 0.2        0.16      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0997232 0.4308363 0.1       0.13     ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.01491469  0.43131083  0.13333333  0.19047619]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10023109 0.46497156 0.1        0.26072859]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09958658 0.46502121 0.2        0.23712156]
dtr: mre:  0.5505536412647365  mae:  1.1224278312361213  rmse:  3.041412263203424
test dtr: mre:  0.4807763720545676  mae:  0.8011988011988012  rmse:  1.885188659104901
rfr: mre:  0.47196296478013944  mae:  0.9661283280262503  rmse:  2.5177575487034094
test rfr: mre:  0.41502395531224573  mae:  0.6823425594141479  rmse:  1.3334625246708418
etr: mre:  0.4729609387599753  mae:  0.9705236558425601  

ETR
KNN
SVR
SR
fitting
predicting
[-0.00663162  0.42090885  0.2         0.3       ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09954354 0.27680293 0.2        0.16666667]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09959306 0.43003163 0.2        0.2       ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0999214  0.34467328 0.13333333 0.28307692]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10018878 0.15757066 0.         0.04794136]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.03735762 0.45147163 0.14285714 0.11111111]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000345 0.31993466 0.14285714 0.16      ]
dtr: mre:  0.5480904452782245  mae:  1.1031088082901555  rmse:  3.0231972973718295
test dtr: mre:  0.42582250039016956  mae:  0.7032051282051281  rmse:  1.5992926368276768
rfr: mre:  0.46959625280549633  mae:  0.9617631151201979  rmse:  2.5074999651058927
test rfr: mre:  0.4253922090665087 

ETR
KNN
SVR
SR
fitting
predicting
[0.09973379 0.35245239 0.13333333 0.13492063]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09979504 0.44686081 0.2        0.15666667]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.00647606  0.36556559  0.13333333  0.15666667]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09994829 0.42468354 0.         0.21484242]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10008346 0.33801303 0.13333333 0.15      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10051582 0.47161507 0.13333333 0.2638009 ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09985202 0.3650015  0.2        0.11333333]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10024245 0.36582647 0.         0.19537727]
dtr: mre:  0.5467517887984208  mae:  1.1023316062176165  rmse:  2.979593227632247
test dtr: mre:  0.45171192861213366  mae:  0.719871794871795  rmse:  1.636451409033556
rfr: mre:  0.47102

ETR
KNN
SVR
SR
fitting
predicting
[0.10000951 0.48623096 0.1        0.168666  ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.04660875  0.39131697  0.1         0.23333333]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1002285  0.4328887  0.13333333 0.22222222]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.099636   0.37555045 0.2        0.19      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10013904 0.36006974 0.13333333 0.16451537]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.02319315 0.48935963 0.14285714 0.2       ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.09981685  0.36463705  0.          0.22671194]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10013705 0.38407763 0.14285714 0.17189499]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10018278 0.44570881 0.13333333 0.24      ]
dtr: mre:  0.5124047888466328  mae:  1.05919689119171  rmse:  2.93283115510142


predicting
[0.05204458 0.04789621 0.         0.04      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10052811 0.03705995 0.         0.02      ]
dtr: mre:  0.2733568075117371  mae:  0.34225352112676055  rmse:  0.7402480387947654
test dtr: mre:  0.17825328407224958  mae:  0.245320197044335  rmse:  0.5807544307391913
rfr: mre:  0.22331409249821427  mae:  0.3006705654194507  rmse:  0.5310652648494417
test rfr: mre:  0.1469871033475149  mae:  0.21171207712078957  rmse:  0.4031981200478266
etr: mre:  0.21075248669550523  mae:  0.2932775994100627  rmse:  0.5067741552273156
test etr: mre:  0.16131814537278416  mae:  0.23183764813915997  rmse:  0.3977357613743177
knn: mre:  0.20456572769953052  mae:  0.27563380281690153  rmse:  0.5087821911831939
test knn: mre:  0.13581588669950737  mae:  0.20195812807881772  rmse:  0.4049011639448201
svr: mre:  0.24731313657348114  mae:  0.33051464034603184  rmse:  0.5421645209209383
test svr: mre:  0.19531838151146366  mae:  0.26623536631015

ETR
KNN
SVR
SR
fitting
predicting
[0.10026027 0.05000595 0.         0.01333333]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09999438 0.03427411 0.         0.01      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10010069 0.04185717 0.         0.06      ]
dtr: mre:  0.2498826291079812  mae:  0.31690140845070425  rmse:  0.7162699998942839
test dtr: mre:  0.17393267651888342  mae:  0.24532019704433497  rmse:  0.5697927228883406
rfr: mre:  0.22269151559748881  mae:  0.2999923170784776  rmse:  0.5290854900882946
test rfr: mre:  0.1501679448191386  mae:  0.21484864319883795  rmse:  0.42825448063944205
etr: mre:  0.2114043111903355  mae:  0.2936753043800987  rmse:  0.5066544823205448
test etr: mre:  0.1621100540603995  mae:  0.23233157935524806  rmse:  0.4258815685516075
knn: mre:  0.20473004694835684  mae:  0.27521126760563386  rmse:  0.5079180445932956
test knn: mre:  0.13129618226600986  mae:  0.19666256157635464  rmse:  0.4166903569264512
svr: mre:  0.246

predicting
[0.09980779 0.0655131  0.         0.01      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09985616 0.01856623 0.         0.00166667]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10007171 0.06045136 0.         0.00073171]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09982325 0.03161496 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.0367415   0.05479936  0.          0.00333333]
dtr: mre:  0.2507042253521127  mae:  0.31830985915492954  rmse:  0.719370467242327
test dtr: mre:  0.17691912972085388  mae:  0.2525862068965517  rmse:  0.5799340686720711
rfr: mre:  0.2208258574667667  mae:  0.29853115579225836  rmse:  0.5294818897276972
test rfr: mre:  0.1519496944011088  mae:  0.2181199418674919  rmse:  0.41869269166075984
etr: mre:  0.2114145554568736  mae:  0.29364208892210886  rmse:  0.5069947639745972
test etr: mre:  0.16137487828949698  mae:  0.23244669700859738  rmse:  0.40821748009793496
kn

ETR
KNN
SVR
SR
fitting
predicting
[0.07743361 0.04097525 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10026821 0.01799547 0.         0.01587302]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10031435 0.07480143 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09995261 0.04117346 0.         0.04761905]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09946026 0.0083232  0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09976521 0.03457465 0.         0.02      ]
dtr: mre:  0.25117370892018775  mae:  0.32253521126760565  rmse:  0.7203754237844309
test dtr: mre:  0.20174466338259442  mae:  0.28793103448275864  rmse:  0.6743379407237279
rfr: mre:  0.2207244572019822  mae:  0.29853163207841804  rmse:  0.5289282896151128
test rfr: mre:  0.14879026785363472  mae:  0.21395569424596195  rmse:  0.42063320528055004
etr: mre:  0.21068372784545927  mae:  0.293038589

ETR
KNN
SVR
SR
fitting
predicting
[0.10024952 0.04339804 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09997137 0.01821328 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10020725 0.02506866 0.         0.02733333]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10041062 0.02094091 0.         0.02666667]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09954428 0.02698565 0.         0.03      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10031186 0.05704014 0.         0.02      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09994341 0.02374409 0.         0.02      ]
dtr: mre:  0.2578638497652582  mae:  0.3267605633802817  rmse:  0.7329610066601722
test dtr: mre:  0.20587027914614123  mae:  0.2812807881773399  rmse:  0.6207830713918151
rfr: mre:  0.2231547620674182  mae:  0.300473539314172  rmse:  0.5301849390284376
test rfr: mre:  0.1518085510407518  mae: 

predicting
[0.10022052 0.00823777 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0994793  0.03796205 0.         0.00333333]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09986347 0.01967777 0.         0.0433908 ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.02318339  0.00808677  0.          0.04      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10039671 0.04420734 0.         0.03666667]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09585549 0.01527846 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.00662404  0.06657355  0.          0.04      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09994586 0.02857722 0.         0.05      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09996592 0.05541638 0.         0.04333333]
dtr: mre:  0.25293427230046944  mae:  0.323943661971831  rmse:  0.7404115292223111
test dtr: mre:  0.2

ETR
KNN
SVR
SR
fitting
predicting
[-0.03277814  0.05190865  0.          0.01587302]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09974446 0.04665622 0.         0.00793651]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10019549 0.06190735 0.         0.03666667]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.01255846 0.04429838 0.         0.03174603]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[-0.03170929  0.05769976  0.          0.02      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10010735 0.03681344 0.         0.02      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09967496 0.03713827 0.         0.00333333]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10013129 0.01591064 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10018557 0.03774494 0.         0.03333333]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10009547 0.0512647

ETR
KNN
SVR
SR
fitting
predicting
[0.10023273 0.01535139 0.         0.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10046638 0.02407834 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09997085 0.02071751 0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09962027 0.01951156 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09991758 0.01758377 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09983476 0.00294589 0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0994915  0.00084686 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10019879 0.00998203 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10027498 0.01901907 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10002113 0.01502752 0.    

ETR
KNN
SVR
SR
fitting
predicting
[0.09988823 0.00225068 0.         0.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09998835 0.02975542 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1002041  0.00708134 0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10049993 0.02131554 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09994761 0.0183611  0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09954197 0.00340476 0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09985651 0.02252175 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0997455  0.00816695 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09984312 0.0192475  0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09975105 0.00701352 0.    

ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.02207307 0.         0.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10006671 0.00602581 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10024636 0.01557435 0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09976313 0.01807118 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09952618 0.00623887 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10021465 0.02140206 0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09973943 0.00698511 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000708 0.02250598 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09993676 0.02943538 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09970895 0.00137143 0.    

ETR
KNN
SVR
SR
fitting
predicting
[0.09952063 0.02175327 0.         0.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09971735 0.01631921 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09981383 0.00938738 0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10006536 0.00096147 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000495 0.02527863 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09985232 0.02038789 0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09984451 0.02038266 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10032655 0.00617365 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10031666 0.02821263 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10004006 0.00345472 0.    

ETR
KNN
SVR
SR
fitting
predicting
[0.1005    0.0167349 0.        0.       ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09956996 0.00578753 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09979716 0.00166667 0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09986277 0.01835687 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09955907 0.00876148 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09977153 0.         0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0996101  0.02347156 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09966033 0.02123086 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09980427 0.00204877 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09977478 0.02531963 0.        

ETR
KNN
SVR
SR
fitting
predicting
[0.10003081 0.01054136 0.         0.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.01435932 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09931335 0.00990751 0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09990075 0.02341477 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10000204 0.02116166 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10001592 0.00569444 0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10028468 0.02148266 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09977606 0.01633888 0.         0.00793651]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09984178 0.02092503 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10052584 0.00300476 0.    

ETR
KNN
SVR
SR
fitting
predicting
[0.09959843 0.00959752 0.         0.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10025925 0.02099326 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09960267 0.         0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09985237 0.0217099  0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10005052 0.0262635  0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1005     0.02251907 0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09962668 0.00334365 0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09977992 0.01218746 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10001827 0.01283333 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10017412 0.02073809 0.    

ETR
KNN
SVR
SR
fitting
predicting
[0.1000771  0.01147848 0.         0.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0995995  0.00261179 0.         0.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09930613 0.01949865 0.         0.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09991037 0.02727093 0.         0.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10002543 0.01958538 0.         0.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10015187 0.02046217 0.         0.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09985126 0.0095415  0.         0.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09980371 0.01952593 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09994441 0.00775623 0.         0.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09990029 0.00474018 0.    

ETR
KNN
SVR
SR
fitting
predicting
[2.1005     2.19397914 2.         2.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.1005     2.73617932 1.85714286 2.2       ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10054039 3.02644675 1.8        2.27509003]
dtr: mre:  0.35399728997289975  mae:  1.0975609756097562  rmse:  1.6809711834264511
test dtr: mre:  0.415044762223071  mae:  1.2290441176470588  rmse:  1.7293320872826812
rfr: mre:  0.3483464552509854  mae:  0.9194220595949476  rmse:  1.3916756809939597
test rfr: mre:  0.3715998484924673  mae:  0.9669311033430759  rmse:  1.3275249138880751
etr: mre:  0.3621747630167088  mae:  0.9299974946991363  rmse:  1.4355919441356737
test etr: mre:  0.37281321127572925  mae:  0.944074058870231  rmse:  1.3482419863231312
knn: mre:  0.39538414634146346  mae:  0.9256097560975611  rmse:  1.413882304327675
test knn: mre:  0.40340591179653673  mae:  1.0633455882352942  rmse:  1.4513178424504105
svr: mre:  0.4081167765706

predicting
[2.10015306 2.82468209 1.8        2.68      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09953935 3.06121155 1.71428571 2.3       ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10057744 3.01113793 1.8        2.62588889]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.1000926  2.790802   1.93333333 2.16666667]
dtr: mre:  0.3717818428184282  mae:  1.178048780487805  rmse:  1.7772608942034558
test dtr: mre:  0.36393883689839573  mae:  1.0992647058823528  rmse:  1.648878856884232
rfr: mre:  0.35015383649501297  mae:  0.9261985700759074  rmse:  1.4019259930041383
test rfr: mre:  0.3735637143955882  mae:  0.9679605794556352  rmse:  1.3756701364197699
etr: mre:  0.36038004445402494  mae:  0.9260010594788828  rmse:  1.4305121135233136
test etr: mre:  0.3774800902826386  mae:  0.9502723419331949  rmse:  1.3827800193174458
knn: mre:  0.3947195121951219  mae:  0.9246341463414633  rmse:  1.409922817066542
test knn: mre:  0.4111380228227654

ETR
KNN
SVR
SR
fitting
predicting
[2.10058729 3.05149552 1.93333333 2.30439162]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09976436 2.74118104 1.8        2.26190476]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09983849 3.12980475 1.7        2.14      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09976264 2.77589496 1.8        2.40772043]
dtr: mre:  0.37205962059620595  mae:  1.0902439024390245  rmse:  1.650425282364272
test dtr: mre:  0.39482954545454546  mae:  1.2349264705882352  rmse:  1.7869599652203434
rfr: mre:  0.3488455831183668  mae:  0.9207716443169683  rmse:  1.3943707061742647
test rfr: mre:  0.3736230272393586  mae:  0.9752565453895068  rmse:  1.3744175816936086
etr: mre:  0.3614590220228575  mae:  0.92763301414271  rmse:  1.4302611372284189
test etr: mre:  0.36686528882724856  mae:  0.9229821278164732  rmse:  1.3784554098802144
knn: mre:  0.3953191056910569  mae:  0.9243902439024391  rmse:  1.4108510666221745
test knn: m

predicting
[2.1005     2.25957971 1.8        1.98122237]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09992057 2.88552302 1.8        2.19047619]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.1005     2.92910567 1.85714286 2.6549596 ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09942381 3.22598542 1.8        2.36311043]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09996227 2.68499502 1.9        2.25315729]
dtr: mre:  0.3780691056910569  mae:  1.1585365853658538  rmse:  1.725533182206466
test dtr: mre:  0.4177908151897122  mae:  1.2742647058823529  rmse:  1.870377878292149
rfr: mre:  0.3486843913967581  mae:  0.9183622406224202  rmse:  1.3894282617108105
test rfr: mre:  0.36598091734343347  mae:  0.9511048017299084  rmse:  1.3470319561381021
etr: mre:  0.36225067890260376  mae:  0.9304249263432032  rmse:  1.4346938500828899
test etr: mre:  0.37158961420314507  mae:  0.9378653373197144  rmse:  1.3596598530720327
knn: mre:  0

predicting
[2.09586572 2.52466375 2.         2.3       ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10041294 2.7637285  2.         2.27520903]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10017995 2.93595227 2.         2.26      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10001009 2.83458816 1.7        2.45      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.1000133  2.86822003 1.85714286 2.30952381]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09967485 2.91772615 1.8        2.24      ]
dtr: mre:  0.3395325203252032  mae:  1.053658536585366  rmse:  1.672726021331965
test dtr: mre:  0.37881409950343775  mae:  1.1783088235294117  rmse:  1.724772040306998
rfr: mre:  0.3495306204864851  mae:  0.9200168380260854  rmse:  1.3905258310677087
test rfr: mre:  0.3689357524113363  mae:  0.9613171657922971  rmse:  1.3161343130592276
etr: mre:  0.36162031509972337  mae:  0.9276082984648882  rmse:  1.432346314800778

ETR
KNN
SVR
SR
fitting
predicting
[3.30690372 3.20285578 4.2        3.8       ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09528408 3.22535034 1.8        2.6       ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09960869 2.84377457 1.93333333 2.16666667]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09985069 2.97651095 1.93333333 2.39      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10052641 2.89509921 1.8        2.34      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10010657 3.00539753 1.85714286 2.28      ]
dtr: mre:  0.3788753387533875  mae:  1.170731707317073  rmse:  1.7680322495990464
test dtr: mre:  0.4451721256684492  mae:  1.3268382352941177  rmse:  1.9089873454875093
rfr: mre:  0.3480169491127697  mae:  0.9219962447875918  rmse:  1.3966950190252707
test rfr: mre:  0.3680631877945259  mae:  0.9604413949682827  rmse:  1.3496933043175827
etr: mre:  0.35846310118961705  mae:  0.9238546992127741  

ETR
KNN
SVR
SR
fitting
predicting
[2.09954738 2.97292259 1.8        2.4       ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.05941666 2.93695344 1.8        2.39      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10037803 2.80863166 1.8        2.20355754]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.90003418 2.8568801  1.6        2.51617857]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09970734 3.02753102 1.85714286 2.38095238]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09978065 3.12464826 1.8        2.52687396]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09956706 2.07245542 1.93333333 2.0952381 ]
dtr: mre:  0.34728319783197825  mae:  1.0951219512195123  rmse:  1.6279492763403067
test dtr: mre:  0.4644393780239368  mae:  1.3363970588235294  rmse:  1.9043995118474293
rfr: mre:  0.35091995698385586  mae:  0.9272559835082397  rmse:  1.3989619307282712
test rfr: mre:  0.37729848367756097  ma

ETR
KNN
SVR
SR
fitting
predicting
[2.09982307 2.86739222 1.9        2.24603175]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10004398 2.94541742 1.85714286 2.22706502]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10035183 2.98357902 1.85714286 2.46666667]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.1005     3.17851928 1.85714286 2.43      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.1005     2.80092431 1.8        2.3015873 ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10031603 2.12585536 1.8        2.09333333]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.09975694 2.86687034 2.33333333 2.26040247]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.10010092 2.78713399 1.8        2.2199098 ]
dtr: mre:  0.3711246612466125  mae:  1.126829268292683  rmse:  1.6548494142399275
test dtr: mre:  0.4327781226126814  mae:  1.246323529411765  rmse:  1.8969209365123931
rfr: mre:  0.349333459

ETR
KNN
SVR
SR
fitting
predicting
[0.09994298 1.52474949 1.28571429 0.31855488]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.47058487 2.11275518 1.85714286 0.32      ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09961465 2.02900748 1.71428571 0.28571429]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.78596979 1.92536245 1.5        0.46      ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.53251741 1.93347727 1.4        0.29365079]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.2154553  1.75021083 1.26666667 0.12      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10020358 2.05726941 1.4        0.4       ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10007013 1.886168   1.5        0.5857039 ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.89990324 3.71968498 3.2        3.16666667]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8985     1.94320843 1.8571

ETR
KNN
SVR
SR
fitting
predicting
[0.8985     1.9479668  1.5        0.44212732]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849449 2.03728095 1.4        0.37978888]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77714977 1.93761335 1.5        0.31      ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.79168358 1.94070524 1.4        0.34      ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.89990789 3.52777178 2.5        3.22337713]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.78556282 2.04675668 1.4        0.47691229]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10023176 1.99604587 1.4        0.42248824]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8985     2.18813538 1.5        0.51333333]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77994177 2.12835772 1.5        0.65      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09961145 1.89212147 1.7142

ETR
KNN
SVR
SR
fitting
predicting
[0.7894349  1.83051729 1.4        0.47043694]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.79183436 1.88983788 1.5        0.48      ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77622682 2.17780943 1.4        0.29      ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77910062 1.907365   2.4        0.39333333]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849685 2.09464335 1.4        0.3       ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.1001602  3.7105498  5.         2.81333333]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8985     1.98679353 1.5        0.43650794]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77609809 1.81764293 1.2        0.24333333]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89850916 1.60164353 1.06666667 0.18      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849679 1.72511557 1.4   

ETR
KNN
SVR
SR
fitting
predicting
[0.10028648 1.67842211 1.4        0.29      ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849687 1.94846628 1.06666667 0.20636365]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90073734 1.57565063 1.4        0.55923399]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.78708506 1.95872732 1.4        0.33333333]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.7898333  1.9410689  1.85714286 0.32      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.0998609  2.25887468 1.4        0.39      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849685 1.76550213 1.4        0.46825397]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8985     2.08847286 1.85714286 0.24      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.99150279 3.86419195 2.46666667 3.37666667]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90091575 2.03047967 1.5   

ETR
KNN
SVR
SR
fitting
predicting
[0.56284934 2.01995177 1.5        0.34580417]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09991907 2.01555695 1.4        0.52028987]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.91227528 3.04834812 1.86666667 3.13492063]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.78747349 2.02507409 2.4        0.39      ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77803504 2.07923227 1.85714286 0.37452162]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849704 1.93427306 1.4        0.35333333]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8985     1.91521039 1.13333333 0.70940948]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77544466 1.90893702 1.3        0.21      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90059579 1.98880121 0.9        0.26984127]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849654 1.82187723 1.7142

ETR
KNN
SVR
SR
fitting
predicting
[0.79362622 2.04461116 1.4        0.54761905]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.90009955 4.11356591 2.9        3.02547486]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8985     1.86086658 1.4        0.14      ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.78790492 2.12371751 1.4        0.42666667]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.09980535 2.06758421 1.4        0.43650794]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77876964 1.9276984  1.4        0.3693496 ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.38084889 1.84864485 1.85714286 0.31746032]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.10038715 1.74421216 1.         0.44923206]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.77596279 2.56869045 1.33333333 0.41853241]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.19641922 1.95914908 1.3333

ETR
KNN
SVR
SR
fitting
predicting
[0.89849703 2.12701003 1.4        0.48028163]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90104401 2.12585778 1.06666667 0.41      ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8985     2.30200075 1.5        0.47      ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.79166393 1.65581285 0.9        0.28571429]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8686964  2.06770255 1.85714286 0.66      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.98345592 4.56456105 3.2        3.10190547]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89849704 2.14328722 1.3        0.45      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.9154912  2.11746972 1.5        0.50520889]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90904293 2.15902271 2.4        0.39666667]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.84015408 2.00882605 1.4   

ETR
KNN
SVR
SR
fitting
predicting
[0.89998698 0.77239218 1.2        0.93650794]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10038622 2.46485649 1.93333333 2.19826627]
dtr: mre:  0.506023720349563  mae:  0.9767790262172283  rmse:  1.9460677833770963
test dtr: mre:  0.3723956582633053  mae:  0.873373015873016  rmse:  1.8225595055410317
rfr: mre:  0.5022475238897851  mae:  0.8158629350314218  rmse:  1.1824627997214245
test rfr: mre:  0.42905825410797116  mae:  0.8931663296065008  rmse:  1.6811281883722617
etr: mre:  0.5150845664088173  mae:  0.8334160513443706  rmse:  1.1738750821232071
test etr: mre:  0.43027578134249644  mae:  0.8917557353547052  rmse:  1.6767432520889518
knn: mre:  0.4518558052434457  mae:  0.8140449438202246  rmse:  1.2982162174020064
test knn: mre:  0.4165710028455827  mae:  0.9183492063492065  rmse:  1.7650573808456564
svr: mre:  0.46573407289678437  mae:  0.7793744281649999  rmse:  1.2173411215922512
test svr: mre:  0.43154646983615963  mae:  0.95

KNN
SVR
SR
fitting
predicting
[0.90035522 2.29086006 1.6        2.62      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90004867 2.71463181 2.4        2.14666667]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10007574 2.29666876 1.85714286 2.17666667]
dtr: mre:  0.5068289637952559  mae:  0.9923220973782769  rmse:  2.0071225736454554
test dtr: mre:  0.41181158018763064  mae:  0.9020238095238093  rmse:  1.847278674862602
rfr: mre:  0.503470035622853  mae:  0.8174640325964413  rmse:  1.1899892438291102
test rfr: mre:  0.42807412388201405  mae:  0.8971602984942457  rmse:  1.7125934644825243
etr: mre:  0.516306066344916  mae:  0.835285929291598  rmse:  1.1734828023797428
test etr: mre:  0.4322224432561593  mae:  0.8908580003985263  rmse:  1.7031170900157342
knn: mre:  0.4513277153558052  mae:  0.8114606741573034  rmse:  1.2963822811283054
test knn: mre:  0.4204499266373216  mae:  0.9227698412698413  rmse:  1.7780418859424167
svr: mre:  0.4515348162112855  ma

KNN
SVR
SR
fitting
predicting
[1.10012826 1.77637673 2.42857143 3.64      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09997909 3.56149044 2.         2.39333333]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89975305 1.6928786  2.14285714 2.08      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90004425 2.32592449 2.14285714 2.39264956]
dtr: mre:  0.46589887640449434  mae:  0.9082397003745317  rmse:  1.8251068821700933
test dtr: mre:  0.3866056200257881  mae:  0.869325396825397  rmse:  1.6571579929763858
rfr: mre:  0.5010752277077006  mae:  0.8153036999666259  rmse:  1.1822071179924478
test rfr: mre:  0.4229555051699637  mae:  0.8865497091603938  rmse:  1.716073656532074
etr: mre:  0.5160904333780582  mae:  0.8369895579686091  rmse:  1.1799109298276487
test etr: mre:  0.4288812911131054  mae:  0.8897039761602847  rmse:  1.7057618314222485
knn: mre:  0.4516304619225967  mae:  0.8132584269662922  rmse:  1.2982388424065225
test knn: mre:  

SR
fitting
predicting
[1.09964634 3.03823497 2.14285714 2.99      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89996324 2.28009076 2.14285714 2.81531601]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09956781 1.8833331  2.14285714 2.19333333]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90001786 2.73728237 2.14285714 1.66      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90046574 1.86023766 2.         2.78      ]
dtr: mre:  0.47825426550145655  mae:  0.9277153558052434  rmse:  1.8639425658976627
test dtr: mre:  0.38570311457916495  mae:  0.9075  rmse:  1.9072815755663126
rfr: mre:  0.5064276742218945  mae:  0.8166363391519813  rmse:  1.18717756255828
test rfr: mre:  0.4256313986177774  mae:  0.8871128187392262  rmse:  1.6883596300891586
etr: mre:  0.5166431319332868  mae:  0.8378151204905724  rmse:  1.1784407433433166
test etr: mre:  0.43888943234874106  mae:  0.9027428514862225  rmse:  1.7023276213533265
knn: mre:  0.

predicting
[1.09996522 3.00905852 2.         1.92857143]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.1001528  1.01561717 0.6        0.85707843]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.9002724  1.99362351 1.8        3.01302816]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90034761 2.98829502 1.86666667 1.62      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09996508 2.30214689 1.8        1.84      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10004726 3.64482601 2.         2.89      ]
dtr: mre:  0.49557428214731586  mae:  0.9691011235955056  rmse:  1.9406264439439933
test dtr: mre:  0.3790396491930106  mae:  0.8498412698412698  rmse:  1.6487115700336585
rfr: mre:  0.5102878264018956  mae:  0.825031782744429  rmse:  1.195873957938891
test rfr: mre:  0.4315680589969631  mae:  0.9006633977901357  rmse:  1.6054301368480897
etr: mre:  0.518355183885274  mae:  0.8399325427516464  rmse:  1.1813966724546292

predicting
[1.1000687  2.79659598 1.8        3.51      ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90049715 2.30213609 1.86666667 2.18      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10016605 3.45644737 2.         2.54      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10010562 2.61130252 2.         2.20976587]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10006157 3.40571634 2.4        2.26      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.0998796  1.98290868 1.66666667 1.51715686]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90030338 2.19152518 2.         2.21      ]
dtr: mre:  0.46146691635455683  mae:  0.899812734082397  rmse:  1.8194359039633787
test dtr: mre:  0.43067313592103507  mae:  0.9548148148148148  rmse:  2.0775653776918066
rfr: mre:  0.503826327750221  mae:  0.8159915373509572  rmse:  1.1848138870215146
test rfr: mre:  0.42519216982018354  mae:  0.8919804557815597  r

SR
fitting
predicting
[1.10037106 0.96528959 1.14285714 0.82539683]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10004593 1.79935274 1.8        3.23809524]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10010886 1.66324476 1.66666667 1.82601   ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90025216 1.95396664 1.93333333 2.69003078]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90512187 2.05324143 2.06666667 1.74603175]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89980734 1.84915484 1.85714286 2.268667  ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90000194 1.87632085 1.8        2.6       ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90035607 1.7415497  1.8        2.53622577]
dtr: mre:  0.5345568039950062  mae:  1.007116104868914  rmse:  2.0506516832087427
test dtr: mre:  0.39521842070161395  mae:  0.8653042328042329  rmse:  1.747531983928064
rfr: mre:  0.5084153554584654  ma

predicting
[1.10019535 2.09463774 2.28571429 2.56449644]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90047028 2.68577891 2.42857143 2.4046668 ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89986591 2.21581003 1.9        2.14333333]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10037808 1.84524979 2.         2.16      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90031604 3.00965579 2.         2.15      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89968574 3.53405986 2.14285714 1.72      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10024374 0.91173473 1.14285714 0.97886192]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.90006489 3.98964572 1.8        2.27      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.89977247 2.11306363 1.26666667 1.78666667]
dtr: mre:  0.4621098626716604  mae:  0.9146067415730336  rmse:  1.8368817527804413
test dtr: mre:  0.344114212

ETR
KNN
SVR
SR
fitting
predicting
[1.52547402 2.74383339 1.3        3.04      ]
dtr: mre:  0.8551242236024844  mae:  1.1  rmse:  2.060076898808477
test dtr: mre:  0.5057408210697685  mae:  0.9660818713450293  rmse:  1.7242629612809548
rfr: mre:  0.5418491664875627  mae:  0.8319358702398381  rmse:  1.2585765694684992
test rfr: mre:  0.5497944223025468  mae:  0.98029515139897  rmse:  1.6138877671673064
etr: mre:  0.6204859344500593  mae:  0.9123191104422261  rmse:  1.2828247423745671
test etr: mre:  0.6035761903867768  mae:  1.0388912656491116  rmse:  1.622357138445368
knn: mre:  0.4509679089026915  mae:  0.7623913043478261  rmse:  1.293415099772567
test knn: mre:  0.48975335239808926  mae:  0.9473684210526315  rmse:  1.6130244325860423
svr: mre:  0.6216131565921741  mae:  0.9456562461568219  rmse:  1.3385171781084266
test svr: mre:  0.549100077907221  mae:  0.9958601164240439  rmse:  1.6443881855842803
str: mre:  0.6351975117857116  mae:  0.9207259350866466  rmse:  1.3600511526832488
te

ETR
KNN
SVR
SR
fitting
predicting
[2.90018287 1.4568707  1.4        3.42      ]
dtr: mre:  0.7865942028985506  mae:  1.0826086956521737  rmse:  2.0262037062144316
test dtr: mre:  0.43083140543666854  mae:  0.872514619883041  rmse:  1.6885663547595087
rfr: mre:  0.5395126144133127  mae:  0.8287133683580622  rmse:  1.2549029817378332
test rfr: mre:  0.5668834530403464  mae:  1.002137166109373  rmse:  1.6339518310557366
etr: mre:  0.622604703441347  mae:  0.9155964988923719  rmse:  1.2840670375877454
test etr: mre:  0.5880769203537006  mae:  1.022404391612225  rmse:  1.6077416082918787
knn: mre:  0.44504658385093177  mae:  0.7571739130434783  rmse:  1.2925002482814953
test knn: mre:  0.46891584195531566  mae:  0.9242105263157894  rmse:  1.587061130398241
svr: mre:  0.5881449608786669  mae:  0.9164307033464638  rmse:  1.3314065170898917
test svr: mre:  0.5506584057669083  mae:  1.007094164448948  rmse:  1.6608505866656131
str: mre:  0.6370986875584305  mae:  0.9275751782389474  rmse:  1.34

predicting
[1.54269527 1.24635114 1.85714286 3.12698413]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.52567057 1.8055679  1.71428571 2.94      ]
dtr: mre:  0.7363354037267082  mae:  1.0108695652173911  rmse:  1.884471461574202
test dtr: mre:  0.5130204071432141  mae:  0.9298245614035088  rmse:  1.5917637387983932
rfr: mre:  0.53519230980969  mae:  0.828011369273533  rmse:  1.2507253035342516
test rfr: mre:  0.5478133238712694  mae:  0.9889525812550779  rmse:  1.5953572524515773
etr: mre:  0.6174228098539142  mae:  0.9102115418134297  rmse:  1.2821660066630474
test etr: mre:  0.5944043596950467  mae:  1.0328005929445996  rmse:  1.5868821572366614
knn: mre:  0.4439958592132506  mae:  0.7571739130434783  rmse:  1.293011390143752
test knn: mre:  0.4686755635527565  mae:  0.9110818713450293  rmse:  1.5394640565416038
svr: mre:  0.6018146031752167  mae:  0.9296985037064143  rmse:  1.3368925063291595
test svr: mre:  0.5378818097255575  mae:  0.9957774253123421  rmse:  1.64371

ETR
KNN
SVR
SR
fitting
predicting
[2.90031279 1.52372844 2.2        3.3       ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.90022037 1.40415244 2.2        3.17      ]
dtr: mre:  0.799223602484472  mae:  1.0652173913043481  rmse:  1.9048652445484606
test dtr: mre:  0.45837026683517906  mae:  0.8707602339181285  rmse:  1.5730109305527773
rfr: mre:  0.5480088888746544  mae:  0.8397450104825689  rmse:  1.2589421003611228
test rfr: mre:  0.5624307451820586  mae:  1.002410672056343  rmse:  1.6013870375754522
etr: mre:  0.6252238375509893  mae:  0.9188071927908208  rmse:  1.2901264635024199
test etr: mre:  0.6054395790595732  mae:  1.0486688951539254  rmse:  1.5985213417951856
knn: mre:  0.44352484472049686  mae:  0.7567391304347826  rmse:  1.29683042023406
test knn: mre:  0.467034400459839  mae:  0.9283333333333333  rmse:  1.5641980317883426
svr: mre:  0.5826578492234138  mae:  0.9097092256126595  rmse:  1.3278812305840921
test svr: mre:  0.5575007646204447  mae:  1.0115120

predicting
[0.10030644 0.20863672 0.06666667 0.00163805]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.89982674 1.22414832 1.3        3.29      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.50112941 1.56765937 1.26666667 2.78      ]
dtr: mre:  0.7719461697722566  mae:  1.082608695652174  rmse:  1.987802534299155
test dtr: mre:  0.5951542852858642  mae:  1.055263157894737  rmse:  1.7635685835808488
rfr: mre:  0.5397290393411556  mae:  0.8295748193554235  rmse:  1.2557117601802912
test rfr: mre:  0.5729470172806539  mae:  1.0147600480043137  rmse:  1.6521462545762524
etr: mre:  0.6187218525616297  mae:  0.9116505623479391  rmse:  1.2832317290320625
test etr: mre:  0.6009130851834364  mae:  1.0362275332962536  rmse:  1.6313569977409788
knn: mre:  0.4399534161490684  mae:  0.7515217391304349  rmse:  1.299511217457497
test knn: mre:  0.46785367264314637  mae:  0.9364035087719298  rmse:  1.613257048873038
svr: mre:  0.6216173376197516  mae:  0.945707669833877

ETR
KNN
SVR
SR
fitting
predicting
[0.09979359 0.21901815 0.         0.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.89969849 1.24523573 1.3        2.96      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.57043394 1.24994846 1.3        3.24      ]
dtr: mre:  0.7275879917184265  mae:  0.9913043478260869  rmse:  1.877598143554896
test dtr: mre:  0.5262649769009419  mae:  0.9523391812865496  rmse:  1.6499694164804635
rfr: mre:  0.5411175324167738  mae:  0.8308628184537215  rmse:  1.2559966165468588
test rfr: mre:  0.5605137151735105  mae:  0.996441752453887  rmse:  1.5783369714079372
etr: mre:  0.6204977074795673  mae:  0.9120215504255722  rmse:  1.2853306843333625
test etr: mre:  0.6029603648822734  mae:  1.0407889288921486  rmse:  1.5737586401262766
knn: mre:  0.45191511387163563  mae:  0.7617391304347827  rmse:  1.2863504827404932
test knn: mre:  0.46257241215574546  mae:  0.9201754385964913  rmse:  1.5245712287336404
svr: mre:  0.60488480799737

predicting
[2.90004057 2.10622276 1.71428571 3.03666667]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.1015     1.75084029 1.33333333 2.83      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.89990452 1.40536334 1.71428571 2.78      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.89979956 1.60578047 1.71428571 2.74      ]
dtr: mre:  0.8428571428571429  mae:  1.1130434782608698  rmse:  2.038135370057447
test dtr: mre:  0.5790068654542339  mae:  1.0  rmse:  1.6669020458930865
rfr: mre:  0.5417540972210068  mae:  0.8337920051896658  rmse:  1.2554986557710595
test rfr: mre:  0.5587884473870732  mae:  0.9968639861118807  rmse:  1.6566790837060068
etr: mre:  0.6200857718058773  mae:  0.9122553178738565  rmse:  1.2819310539061415
test etr: mre:  0.6033102002937271  mae:  1.0399134382169475  rmse:  1.6576628327777772
knn: mre:  0.4532505175983436  mae:  0.7660869565217391  rmse:  1.3026139353654804
test knn: mre:  0.4902114759834058  mae:  0.946871

ETR
KNN
SVR
SR
fitting
predicting
[2.89993226 1.19861427 2.2        3.02      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.34748548 1.40448828 1.2        2.58      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.90069829 1.45738402 1.53333333 3.42      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.52191475 1.58663791 1.26666667 2.76190476]
dtr: mre:  0.7760869565217392  mae:  1.0391304347826087  rmse:  1.9298550397749086
test dtr: mre:  0.5497216063663433  mae:  0.9798245614035087  rmse:  1.6933681975261372
rfr: mre:  0.5420306487535024  mae:  0.8342743487428711  rmse:  1.257688801193369
test rfr: mre:  0.5592283006526643  mae:  0.9994579948659845  rmse:  1.6156042497639433
etr: mre:  0.6232331230180623  mae:  0.9153820537733708  rmse:  1.286867533668796
test etr: mre:  0.5982369808687903  mae:  1.0407433836421238  rmse:  1.5900028298313518
knn: mre:  0.44267598343685305  mae:  0.7528260869565218  rmse:  1.2969959426305804
test knn: mr

ETR
KNN
SVR
SR
fitting
predicting
[1.09984798 1.02583677 0.93333333 1.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09958331 1.01126259 1.         1.00333333]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.97662794 1.00745979 1.         1.00333333]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09967399 1.0061031  0.93333333 1.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09999811 1.02127814 1.         1.00463714]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.96102258 1.01300955 1.         1.001011  ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10009417 1.10945351 1.         1.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.94373251 1.02461331 1.         1.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.1005     1.01831705 1.         1.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.9373153  1.01944696 1.    

ETR
KNN
SVR
SR
fitting
predicting
[1.1005     1.02125434 0.93333333 1.00235657]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09975971 1.02496206 1.         1.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10030692 1.03084426 0.93333333 1.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09998769 1.02595151 0.93333333 1.00383743]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09995877 0.9979782  0.93333333 1.00084476]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.1005     1.00288043 0.9        1.00287609]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09977235 0.99729278 1.         1.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.93499774 1.02663086 1.         1.00333333]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09979138 1.0262169  0.93333333 1.01      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.95713051 1.01949276 1.    

ETR
KNN
SVR
SR
fitting
predicting
[1.10003175 1.02060274 0.9        1.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.98405167 1.01760219 1.         1.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.94739296 1.03155036 1.         1.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09990195 1.00200646 1.         1.0007447 ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10003259 1.66703212 1.3        1.12698413]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.96697701 1.02474837 1.         1.00429083]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.962993   0.99732347 1.         1.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09866926 1.02401142 0.9        1.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.93492635 1.02696853 0.93333333 1.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10021267 1.01993749 0.9333

ETR
KNN
SVR
SR
fitting
predicting
[1.10000295 1.01869001 1.         1.00360714]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.0999494  1.02299517 1.         1.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10038979 1.00780822 1.         1.        ]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10044555 1.0006167  1.         1.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.0998043  1.02120521 1.         1.02      ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09983089 0.99270902 0.93333333 1.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.94169756 1.03300425 1.         1.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.1005     1.02071411 1.         1.00793651]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10017233 1.02257247 1.         1.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.00885476 1.01842239 0.9   

ETR
KNN
SVR
SR
fitting
predicting
[1.09992641 1.01025648 1.         1.        ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10036244 0.99615387 1.         1.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10018711 1.00889143 1.         1.00793651]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10004729 1.00510611 0.85714286 1.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10013742 1.1162288  1.         1.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.00227312 1.01089125 1.         1.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.93661402 1.0150021  1.         1.01      ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10049983 1.03091134 0.93333333 1.        ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.93651787 1.00383839 0.9        1.00666667]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09988145 1.03005275 1.    

ETR
KNN
SVR
SR
fitting
predicting
[1.10024527 1.02067203 1.         1.00105392]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.93794442 1.00932631 0.9        1.00333333]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09953555 1.02401535 0.9        1.00262504]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10042277 1.02226929 1.         1.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.9381232  1.02726187 0.9        1.        ]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09938912 1.00393144 0.85714286 1.02      ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09992621 1.0043209  1.         1.00208447]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09998129 1.12619597 1.         1.00024218]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.95010806 1.02628359 0.93333333 1.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09996297 1.01094778 1.    

ETR
KNN
SVR
SR
fitting
predicting
[1.1005    1.0228841 0.9       1.       ]
fold number:  2
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10037836 1.02456546 0.93333333 1.        ]
fold number:  3
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10015955 1.0358534  1.         1.00018862]
fold number:  4
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10023115 1.01553497 1.         1.        ]
fold number:  5
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10006353 1.00888877 1.         1.00423501]
fold number:  6
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.98302695 0.98971522 1.         1.        ]
fold number:  7
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.1005     1.02701392 1.         1.        ]
fold number:  8
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09994502 1.02669609 0.93333333 1.00319678]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09978243 1.00666175 1.         1.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09969008 1.02742834 0.93333333

predicting
[1.10015341 1.34577722 1.5        0.83650794]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.15889323 1.21666453 1.5        0.76111111]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.099501   1.08899908 1.4        0.86      ]
dtr: mre:  0.5917987061353344  mae:  1.9544491525423726  rmse:  4.524428973235606
test dtr: mre:  0.5294538733029939  mae:  2.11968085106383  rmse:  4.864184248784208
rfr: mre:  0.6959840233712671  mae:  2.1436951437348837  rmse:  4.597723810195856
test rfr: mre:  0.530866252511305  mae:  1.7763253902090868  rmse:  3.7122591138471845
etr: mre:  0.7657639945818273  mae:  2.183772340152183  rmse:  4.575251180132458
test etr: mre:  0.6433635014185966  mae:  1.9103188530702884  rmse:  3.789604085379653
knn: mre:  0.7977705490069006  mae:  2.2421186440677965  rmse:  4.520292757729352
test knn: mre:  0.6114592754837492  mae:  1.938936170212766  rmse:  3.746181931656764
svr: mre:  0.6587992153515211  mae:  2.2302251750128086  rmse:

ETR
KNN
SVR
SR
fitting
predicting
[1.0995    0.8847324 1.4       0.82375  ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[2.00406233 2.01831097 1.9        2.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10015504 1.0250029  1.57142857 0.7       ]
dtr: mre:  0.5559620527930738  mae:  1.903171545968156  rmse:  4.435495108404541
test dtr: mre:  0.6551279455054733  mae:  2.3050290135396514  rmse:  5.148445165903839
rfr: mre:  0.7031583436466363  mae:  2.1624962192718975  rmse:  4.6300512840031
test rfr: mre:  0.5430401894496886  mae:  1.808742690334423  rmse:  3.8569769729571584
etr: mre:  0.7564854384264885  mae:  2.1599586794212935  rmse:  4.5381484781417525
test etr: mre:  0.6293408730232588  mae:  1.8897457768599328  rmse:  3.72467512291668
knn: mre:  0.7934170324465394  mae:  2.2431355932203396  rmse:  4.514052624319561
test knn: mre:  0.6093075980847809  mae:  1.9104255319148937  rmse:  3.8130627855086745
svr: mre:  0.656731287994207  mae:  2.225

ETR
KNN
SVR
SR
fitting
predicting
[0.73987622 1.28927234 1.57142857 0.86507937]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.8308034  1.43294499 1.6        0.80377778]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09972565 1.0062766  1.5        0.84126984]
dtr: mre:  0.5579238280925468  mae:  1.9394774011299436  rmse:  4.564525142288015
test dtr: mre:  0.5633007870732658  mae:  2.1021276595744682  rmse:  4.852949369094996
rfr: mre:  0.6991017073238641  mae:  2.148799390494461  rmse:  4.607306856316396
test rfr: mre:  0.524946507128236  mae:  1.7581678619806067  rmse:  3.7638976250736738
etr: mre:  0.7713708278516677  mae:  2.186433440880342  rmse:  4.572170145721984
test etr: mre:  0.637408895912224  mae:  1.8937337454111058  rmse:  3.7241244854447273
knn: mre:  0.7909059231666126  mae:  2.2239830508474574  rmse:  4.501145064649808
test knn: mre:  0.6003723139194699  mae:  1.9138297872340426  rmse:  3.7261507029400973
svr: mre:  0.6554987470838926  mae: 

ETR
KNN
SVR
SR
fitting
predicting
[1.14747019 1.06701369 1.57142857 0.882     ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.10586231 2.08488719 1.6        2.        ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.87893618 0.76383606 1.5        0.79      ]
dtr: mre:  0.5354798129507137  mae:  1.8681497175141242  rmse:  4.340641738710337
test dtr: mre:  0.5666042734178067  mae:  2.179432624113475  rmse:  4.764837664492422
rfr: mre:  0.7078512783153942  mae:  2.167089719748151  rmse:  4.634545599891775
test rfr: mre:  0.5380620712107579  mae:  1.7882383832499809  rmse:  3.723105891534824
etr: mre:  0.7543712480373382  mae:  2.160379108147738  rmse:  4.550624909096917
test etr: mre:  0.6314568880406417  mae:  1.871923337626645  rmse:  3.676754607413276
knn: mre:  0.7905933457539345  mae:  2.2263559322033895  rmse:  4.500576367546037
test knn: mre:  0.5993983576184683  mae:  1.901063829787234  rmse:  3.665512953119852
svr: mre:  0.6586726048061194  mae:  2.2

ETR
KNN
SVR
SR
fitting
predicting
[1.10017856 1.07075329 1.57142857 0.9004    ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09996268 0.89896752 1.4        0.75133333]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.0995     1.14276302 1.4        0.77777778]
dtr: mre:  0.5586681451130513  mae:  1.9000706214689262  rmse:  4.348698681887028
test dtr: mre:  0.6664343351859902  mae:  2.4445035460992908  rmse:  5.789625013940297
rfr: mre:  0.7012681374324894  mae:  2.1619615797969773  rmse:  4.617551607916103
test rfr: mre:  0.531319291200681  mae:  1.7661850993009995  rmse:  3.802404961641643
etr: mre:  0.7609939238785819  mae:  2.1716261062906845  rmse:  4.554435063296418
test etr: mre:  0.6339879488852984  mae:  1.8820240002986584  rmse:  3.7464099880925836
knn: mre:  0.7942880091958673  mae:  2.23364406779661  rmse:  4.503828428574517
test knn: mre:  0.6104432922342423  mae:  1.9274468085106382  rmse:  3.7007126356845736
svr: mre:  0.6519758535623019  mae: 

ETR
KNN
SVR
SR
fitting
predicting
[1.07986798 1.46250405 1.57142857 0.79      ]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09970142 0.95144046 1.5        0.76      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.02154039 1.29405679 1.6        0.787     ]
dtr: mre:  0.5832317505330398  mae:  1.907485875706215  rmse:  4.501965565419241
test dtr: mre:  0.6437177374875072  mae:  2.199822695035461  rmse:  4.787469472152782
rfr: mre:  0.7001979506548278  mae:  2.1536762895750075  rmse:  4.607639195377557
test rfr: mre:  0.5326328759908697  mae:  1.7821333956946686  rmse:  3.7955134598576628
etr: mre:  0.7608162000354349  mae:  2.1771956257658105  rmse:  4.56429370947801
test etr: mre:  0.6277616475099748  mae:  1.8884717855540643  rmse:  3.7814635681185913
knn: mre:  0.7881883243726133  mae:  2.2227966101694916  rmse:  4.491758895051419
test knn: mre:  0.5985285878339028  mae:  1.89063829787234  rmse:  3.7786411137583875
svr: mre:  0.6590301778955594  mae:  

ETR
KNN
SVR
SR
fitting
predicting
[0.72788337 1.2717281  1.4        0.76490909]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[0.74078477 1.17930152 1.53333333 0.72      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09995444 1.18632603 1.7        0.84833333]
dtr: mre:  0.5542851287162913  mae:  1.8961158192090397  rmse:  4.429359704536142
test dtr: mre:  0.6197374713424545  mae:  2.1530141843971635  rmse:  5.060137501527734
rfr: mre:  0.6969135569806285  mae:  2.1471051106851617  rmse:  4.601170514563449
test rfr: mre:  0.5457952016114949  mae:  1.7913442085302436  rmse:  3.715579740064905
etr: mre:  0.7536772824537752  mae:  2.1586729084919263  rmse:  4.532046102351121
test etr: mre:  0.6348018432853848  mae:  1.8745809725298457  rmse:  3.657181033951916
knn: mre:  0.7942342990409262  mae:  2.240677966101695  rmse:  4.500928055553205
test knn: mre:  0.6114232153270722  mae:  1.9263829787234044  rmse:  3.7767639703064773
svr: mre:  0.6591795515552291  mae:

ETR
KNN
SVR
SR
fitting
predicting
[1.09969715 0.9076127  1.7        0.75591799]
fold number:  9
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09950256 1.07909538 1.4        0.71      ]
fold number:  10
DTR
RFR
ETR
KNN
SVR
SR
fitting
predicting
[1.09990337 0.95898576 1.4        0.80952381]
dtr: mre:  0.5770271017459322  mae:  1.884816384180791  rmse:  4.394357195394255
test dtr: mre:  0.5410591857541581  mae:  2.1984042553191485  rmse:  5.019478452579028
rfr: mre:  0.6947512815736615  mae:  2.143741276038802  rmse:  4.5999001257084275
test rfr: mre:  0.542971553913538  mae:  1.813910188298283  rmse:  3.68467848832992
etr: mre:  0.7593316845463343  mae:  2.165141615408162  rmse:  4.55158268366313
test etr: mre:  0.6179464750717031  mae:  1.8733952042939155  rmse:  3.5718751956648744
knn: mre:  0.7935147495883083  mae:  2.2362711864406775  rmse:  4.496198761793909
test knn: mre:  0.6023222541591795  mae:  1.9185106382978723  rmse:  3.6664666784112554
svr: mre:  0.6568785670749946  mae:  2.